name: cus_movil
description: "App móvil de Clave Única Sanjuanense"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.1.38
  intl: ^0.20.2
  google_maps_flutter: ^2.12.1
  http: ^1.4.0
  xml: ^6.5.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  provider: ^6.1.5
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.4
  confetti: ^0.7.0
  file_picker: ^8.1.2
  path: ^1.9.0
  flutter_pdfview: ^1.2.7
  path_provider: ^2.1.2
  liquid_progress_indicator_v2: ^0.5.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  lottie: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1 # Actualizado al lint moderno compatible con SDK 3.5.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/logo_sjr.png
    - assets/mejor_sanjuan.png
    - assets/fondo.png
    - assets/fondo_2.png
    - assets/logo_blanco.png
    - assets/codigos_postales_queretaro.xml
    - assets/logo_claveunica.png
    - assets/logo_claveunica_sinfondo.png
    - assets/ine.png
    - assets/Acta_nacimiento.png
    - assets/Comprobante_domicilio.png
    - assets/Acta_matrimonio.png
    - assets/Acta_concubinato.png
    - assets/documentoscorrectos.png
    - assets/Correo Electronico.png
    - assets/Curp.png
    - assets/Direccion.png
    - assets/Estado Civil.png
    - assets/Fecha de Nacimiento.png
    - assets/Informacion de contacto.png
    - assets/informacion laboral.png
    - assets/informacion personal.png
    - assets/Nacionalidad.png
    - assets/Ocupacion.png
    - assets/telefono.png
    - assets/logo_institucional.png
    - .env
    