name: cus_movil
description: "App móvil de Clave Única Sanjuanense"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^29.1.38
  intl: ^0.20.2
  google_maps_flutter: ^2.12.1
  http: ^1.4.0
  xml: ^6.5.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  provider: ^6.1.5
  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.4
  confetti: ^0.7.0 # o la versión más reciente compatible

  
  # File picker plugin - versión actualizada y compatible
  file_picker: ^8.1.2
  
  # Path utilities para manejo de rutas de archivos
  path: ^1.9.0
  flutter_pdfview: ^1.2.7
  path_provider: ^2.1.2
  liquid_progress_indicator_v2: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_sjr.png
    - assets/mejor_sanjuan.png
    - assets/fondo.png
    - assets/fondo_2.png
    - assets/logo_blanco.png
    - assets/codigos_postales_queretaro.xml
    - assets/logo_claveunica.png
    - assets/logo_claveunica_sinfondo.png
    - assets/ine.png
    - assets/acta_nacimiento.png
    - assets/curp.png
    - assets/comprobante_domicilio.png
    - assets/acta_matrimonio.png
    - assets/acta_concubinato.png
    - assets/documentoscorrectos.png
